# docker run --rm -p 4317:4317 -p 4318:4318 -p 8889:8889 \
#     -v $(pwd)/collector-config.yaml:/etc/collector-config.yaml \
#     otel/opentelemetry-collector \
#     --config /etc/collector-config.yaml

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "airflow"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
